### ISSUE TITLE
IllegalArgumentException: UUID string too large

### ISSUE THREAD

**Issue by vc** [TheSilentPro/HeadDB#17]
mc Paper v1.16.5

Config: default
Debug: true

[21:18:36 INFO]: [HeadDB] Enabling HeadDB v2.4.0
[21:18:36 INFO]: [HeadDB] [INFO]: Loading HeadDB - 2.4.0
[21:18:36 INFO]: [HeadDB] [DEBUG]: Starting metrics...
[21:18:36 INFO]: [HeadDB] [DEBUG]: Registering listeners...
[21:18:36 INFO]: [HeadDB] [DEBUG]: Registering commands...
[21:18:36 INFO]: [HeadDB] [DEBUG]: Initializing Database... (SYNC)
[21:18:36 INFO]: [HeadDB] [DEBUG]: Caching heads from: alphabet
[21:18:37 INFO]: [HeadDB] [DEBUG]: Caching heads from: animals
[21:18:37 INFO]: [HeadDB] [DEBUG]: Caching heads from: blocks
[21:18:38 INFO]: [HeadDB] [DEBUG]: Caching heads from: decoration
[21:18:38 ERROR]: Error occurred while enabling HeadDB v2.4.0 (Is it up to date?)
java.lang.IllegalArgumentException: UUID string too large
        at java.util.UUID.fromString1(UUID.java:264) ~[?:?]
        at java.util.UUID.fromString(UUID.java:258) ~[?:?]
        at tsp.headdb.database.HeadDatabase.getHeadsNoCache(HeadDatabase.java:149) ~[?:?]
        at tsp.headdb.database.HeadDatabase.update(HeadDatabase.java:170) ~[?:?]
        at tsp.headdb.HeadDB.onEnable(HeadDB.java:61) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-753]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-753]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-753]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-753]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-753]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-753]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-753]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-753]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-753]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[21:18:38 INFO]: [HeadDB] Disabling HeadDB v2.4.0

**Comment by TheSilentPro** [comment]
Should be fixed now (api issue)
