### ISSUE TITLE
Error at index 0 in: "jk1f4e60"

### ISSUE THREAD

**Issue by joex92** [TheSilentPro/HeadDB#20]
**Describe the bug**
The plugin is not starting

**Information**
Plugin Version: `2.4.3`
Server Version: `Purpur version git-Purpur-1427 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8bb5a93 on ver/1.17.1)`

**Errors**
```yaml
[09:01:25] [Server thread/INFO]: [HeadDB] Enabling HeadDB v2.4.3
[09:01:25] [Server thread/INFO]: [HeadDB] [INFO]: Loading HeadDB - 2.4.3
[09:01:28] [Server thread/ERROR]: Error occurred while enabling HeadDB v2.4.3 (Is it up to date?)
java.lang.NumberFormatException: Error at index 0 in: "jk1f4e60"
	at java.lang.NumberFormatException.forCharSequence(NumberFormatException.java:83) ~[?:?]
	at java.lang.Long.parseLong(Long.java:797) ~[?:?]
	at java.util.UUID.fromString1(UUID.java:283) ~[?:?]
	at java.util.UUID.fromString(UUID.java:258) ~[?:?]
	at tsp.headdb.database.HeadDatabase.getHeadsNoCache(HeadDatabase.java:169) ~[HeadDB-2.4.3.jar:?]
	at tsp.headdb.database.HeadDatabase.update(HeadDatabase.java:206) ~[HeadDB-2.4.3.jar:?]
	at tsp.headdb.HeadDB.onEnable(HeadDB.java:46) ~[HeadDB-2.4.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Purpur-1427]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Purpur-1427]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1427]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Purpur-1427]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Purpur-1427]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:734) ~[patched_1.17.1.jar:git-Purpur-1427]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:353) ~[patched_1.17.1.jar:git-Purpur-1427]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[patched_1.17.1.jar:git-Purpur-1427]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1427]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
[09:01:28] [Server thread/INFO]: [HeadDB] Disabling HeadDB v2.4.3
```

Already tried deleting the plugin's config folder, so it recreates it, but still get the error...

**Comment by TheSilentPro** [comment]
Should be fixed in 2.4.4
Redownload the plugin
