### ISSUE TITLE
Can not fetch heads due to parsing json failed while fetching head info

### ISSUE THREAD

**Issue by non-ke** [TheSilentPro/HeadDB#54]
**Describe the bug**
**https://heads.pages.dev/archive/humans.json returns an incomplete json string**.Prasing json failed while fetching head info due to wrong json syntax in the response from the head database api.And the plugin haven't any checking or correction before parsing json to object.
Relative code(in headdb/implementation/requester/Requester.java):
```java
public void fetchAndResolve(Category category, Consumer<List<Head>> heads) {
        try {  
            fetch(category, response -> {  
                List<Head> result = new ArrayList<>();  
                if (response.code() != 200) {  
                    heads.accept(result);  
                    return;  
                }  
                JsonArray main = JsonParser.parseString(response.response()).getAsJsonArray();  
               ...
```
**Information**
Plugin Version: 5.0.0-rc7
Server Version: paper mc-1.20.1-98
Client Version: 1.20.1

**Errors**
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 3350836 path $[10557].uuid
at com.google.gson.internal.Streams.parse(Streams.java:61) ~[gson-2.10.jar:?]
        at com.google.gson.JsonParser.parseReader(JsonParser.java:102) ~[gson-2.10.jar:?]
        at com.google.gson.JsonParser.parseReader(JsonParser.java:70) ~[gson-2.10.jar:?]
        at com.google.gson.JsonParser.parseString(JsonParser.java:51) ~[gson-2.10.jar:?]
        **at tsp.headdb.implementation.requester.Requester.lambda$fetchAndResolve$0(Requester.java:42) ~[HeadDB.jar:?]**
        at tsp.headdb.implementation.requester.Requester.fetch(Requester.java:91) ~[HeadDB.jar:?]
        at tsp.headdb.implementation.requester.Requester.fetchAndResolve(Requester.java:35) ~[HeadDB.jar:?]
        at tsp.headdb.implementation.head.HeadDatabase.lambda$getHeadsNoCache$1(HeadDatabase.java:39) ~[HeadDB.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-98]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-98]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 3350836 path $[10557].uuid
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1657) ~[gson-2.10.jar:?]
        at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1042) ~[gson-2.10.jar:?]
        at com.google.gson.stream.JsonReader.nextName(JsonReader.java:796) ~[gson-2.10.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:783) ~[gson-2.10.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725) ~[gson-2.10.jar:?]
        at com.google.gson.internal.Streams.parse(Streams.java:49) ~[gson-2.10.jar:?]
        ... 13 more

**Screenshots**

**Comment by TheSilentPro** [comment]
This seems to be for the fallback archive provider ill update it now, the plugin should work fine now correct?

**Comment by non-ke** [comment]
The problem has been fixed, but I recommend handling MalformedJsonException in the code to avoid head update failing. In addition,if head data update fails and there is no data in my minecraft server, plugin throws NullPointerException if player opens HeadDB category GUI.
Relative code:
```java
    //tsp.headdb.core.api.HeadAPI | line 108
    //If a category has not been updated, can not find the category using getHeadsMap().get(category)) method 
    @Nonnull
    public static List<Head> getHeads(Category category) {
        return getHeadsMap().get(category)); // returns null if category is not exists in the heads map key list
    }
```
```java
    //tsp.headdb.implementation.category.Category | line 61
    @Nonnull
    public ItemStack getItem(UUID receiver) {
        if (item == null) {
            //if the category updates head data failed before,getHeads(this) returns null and throws unprocessed NPE
            HeadAPI.getHeads(this).stream().findFirst()
            ...
    }
```

**Comment by TheSilentPro** [comment]
Fixed
