### ISSUE TITLE
[Mohist 1.12.2] Issue with enabling HeadDB

### ISSUE THREAD

**Issue by Agrrox** [TheSilentPro/HeadDB#6]
Issue: Mohist prints errors when it tries to enable the plugin.

## Server Setup:

Mohist version: 1.12.2 build #192
<details>
<summary>Plugins:</summary>

```
AdvancedBan (v2.3.0)
AnnouncerPlus (v1.2.3)
BKCommonLib (v1.16.5-v3-SNAPSHOT)
BannerMaker (v1.9.0)
BannerText (v1.12.2-1)
BetterBrushes (v1.0.0.140406)
CommandSigns (v1.6.7)
DeluxeMenus (v1.13.3-Release)
Essentials (v2.18.2.0)
EssentialsSpawn (v2.18.2.0)
F3NPerm (v2.5)
HeadDB (v2.2)
HolographicExtension (v1.10.9)
ItemJoin (v5.2.1-RELEASE-b678)
LastLoginAPI (v1.4.3)
LightCleaner (v1.16.5-v1)
LuckPerms (v5.2.76)
PlaceholderAPI (v2.10.9)
ProtocolLib (v4.5.1)
RelativeCoordCalculator (v0.5)
SchematicBrush (v0.5.2-20)
Sledgehammer (v0.4.2)
TabTPS (v1.3.3)
TouchscreenHolograms (v1.4.2)
Vault (v1.6.7-b${env.TRAVIS_BUILD_NUMBER})
VentureChat (v2.21.1)
VoxelSniper (v5.171.0-CC_COMPAT-SNAPSHOT)
WorldEdit (v6.1.9;caf0ad9)
WorldGuard (v6.2.2-SNAPSHOT;8eeab68)
WorldGuardExtraFlags (v4.1.4)
```
</details>
<details>
<summary>Mods:</summary>

```
Aroma1997Core-1.12.2-2.0.0.2.b167
AromaBackup-1.12.2-3.0.0.0.b135
CubicChunks-1.12.2-0.0.1185.0-SNAPSHOT-all
CubicWorldGen-1.12.2-0.0.145.0-SNAPSHOT-all
bannermod-1.1.0
ccpregen-0.0.21
morecompressions-3.0.0.0.b135
rhino-1.7.12
terra121-0.1.5.1.
terramap-1.0.0-beta6.6
worldedit-forge-mc1.12.2-6.1.11-cubicchunks-SNAPSHOT-dist

```

</details>

## Error Messages:
<details>
<summary>error message when enabling:</summary>
  
```powershell
[20:37:29] [Server thread/ERROR] [Mohist]: Error occurred while enabling HeadDB v2.2 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.scheduler.BukkitScheduler.runTask(Lorg/bukkit/plugin/Plugin;Ljava/util/function/Consumer;)V
	at tsp.headdb.HeadDB.onEnable(HeadDB.java:48) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:177) ~[JavaPlugin.class:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:318) [JavaPluginLoader.class:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:399) [SimplePluginManager.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:477) [CraftServer.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:418) [CraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:389) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:316) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
```
</details>

<details>
<summary>error message when running commands:</summary>  

```powershell
[20:38:11] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Agrro issued server command: /hdb
[20:38:13] [Server thread/ERROR] [Mohist]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'hdb' in plugin HeadDB v2.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[PluginCommand.class:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[SimpleCommandMap.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[CraftServer.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1588) ~[pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1427) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:46) ~[la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:9) ~[la.class:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_275]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_275]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.NoSuchFieldError: PLAYER_HEAD
	at tsp.headdb.api.Head.getItemStack(Head.java:36) ~[?:?]
	at tsp.headdb.database.Category.getItem(Category.java:45) ~[?:?]
	at tsp.headdb.database.Category.getItem(Category.java:49) ~[?:?]
	at tsp.headdb.inventory.InventoryUtils.openDatabase(InventoryUtils.java:129) ~[?:?]
	at tsp.headdb.command.Command_headdb.onCommand(Command_headdb.java:31) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:43) ~[PluginCommand.class:?]
	... 15 more
```

</details>

**Comment by TheSilentPro** [comment]
The plugin wasn't really made to work on these type of hybrids, though it might on some but on this one seems some stuff is missing hence the `java.lang.NoSuchMethodError`.
Only suggestion i can give is trying it on a 1.16 server instead.

Edit: Actually 1.12.2 and below use interget ids still. So one of the errors is for that, i will be trying to add backwards support in the future maybe.
