### ISSUE TITLE
Main Buttons Bug

### ISSUE THREAD

**Issue by Somikyy** [TheSilentPro/HeadDB#72]
[22:04:59 ERROR]: Could not pass event InventoryClickEvent to HeadDB v5.0.0-rc.10
java.lang.ExceptionInInitializerError: null
        at tsp.headdb.core.util.anvilgui.AnvilGUI$Builder.<init>(AnvilGUI.java:385) ~[HeadDB.jar:?]
        at tsp.headdb.core.command.CommandMain.lambda$handle$7(CommandMain.java:98) ~[HeadDB.jar:?]
        at tsp.nexuslib.inventory.Button.onClick(Button.java:58) ~[HeadDB.jar:?]
        at tsp.nexuslib.inventory.Page.handleClick(Page.java:40) ~[HeadDB.jar:?]
        at tsp.nexuslib.inventory.Pane.onClick(Pane.java:60) ~[HeadDB.jar:?]
        at tsp.nexuslib.inventory.PaneListener.onClick(PaneListener.java:24) ~[HeadDB.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor169.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-385]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-385]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-385]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3117) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-385]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1458) ~[paper-1.20.4.jar:git-Paper-385]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-385]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1435) ~[paper-1.20.4.jar:git-Paper-385]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[paper-1.20.4.jar:git-Paper-385]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1550) ~[paper-1.20.4.jar:git-Paper-385]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.20.4.jar:git-Paper-385]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-385]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: AnvilGUI does not support server version "1_20_R3"
        at tsp.headdb.core.util.anvilgui.version.VersionMatcher.match(VersionMatcher.java:32) ~[HeadDB.jar:?]
        at tsp.headdb.core.util.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:43) ~[HeadDB.jar:?]
        ... 30 more
Caused by: java.lang.ClassNotFoundException: tsp.headdb.core.util.anvilgui.version.Wrapper1_20_R3
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:421) ~[?:?]
        at java.lang.Class.forName(Class.java:412) ~[?:?]
        at tsp.headdb.core.util.anvilgui.version.VersionMatcher.match(VersionMatcher.java:28) ~[HeadDB.jar:?]
        at tsp.headdb.core.util.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:43) ~[HeadDB.jar:?]
        ... 30 more

**Comment by TheSilentPro** [comment]
This is only for search button correct?

**Comment by Somikyy** [comment]
> This is only for search button correct?

nope, for all 3 buttons in the underpanel

**Comment by l3nnartt** [comment]
should be fixed with #74 , can be closed
