### ISSUE TITLE
[HeadDB] Task #11 for HeadDB v2.2 generated an exception

### ISSUE THREAD

**Issue by Kastello1** [TheSilentPro/HeadDB#8]
I get the following error with headdb and latest papercraft version:

[18:18:47] [Server thread/INFO]: [HeadDB] [DEBUG]: Caching heads from: alphabet
[18:18:47] [Server thread/INFO]: [HeadDB] [DEBUG]: Caching heads from: animals
[18:18:48] [Server thread/INFO]: [HeadDB] [DEBUG]: Caching heads from: blocks
[18:18:48] [Server thread/INFO]: [HeadDB] [DEBUG]: Caching heads from: decoration
[18:18:48] [Server thread/WARN]: [HeadDB] Task #11 for HeadDB v2.2 generated an exception
java.lang.IllegalArgumentException: UUID string too large
	at java.util.UUID.fromString1(UUID.java:264) ~[?:?]
	at java.util.UUID.fromString(UUID.java:258) ~[?:?]
	at tsp.headdb.database.HeadDatabase.getHeadsNoCache(HeadDatabase.java:131) ~[?:?]
	at tsp.headdb.database.HeadDatabase.update(HeadDatabase.java:151) ~[?:?]
	at tsp.headdb.HeadDB.lambda$onEnable$1(HeadDB.java:48) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:102) ~[patched_1.16.5.jar:git-Paper-714]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-714]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1077) ~[patched_1.16.5.jar:git-Paper-714]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-714]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by TheSilentPro** [comment]
Still have this issue?
If so:
try the 2.3 version
Latest being what version? 1.16.5? Is it just when the plugin loads?
