### ISSUE TITLE
java.lang.IllegalArgumentException: UUID string too large (Multiple Occurances)

### ISSUE THREAD

**Issue by weiblecr** [TheSilentPro/HeadDB#9]
#### Example from Task #23
-----------------------------------------------
[12:00:10] [Server thread/WARN]: [HeadDB] Task #23 for HeadDB v2.2 generated an exception
java.lang.IllegalArgumentException: UUID string too large
        at java.util.UUID.fromString(UUID.java:199) ~[?:?]
        at tsp.headdb.database.HeadDatabase.getHeadsNoCache(HeadDatabase.java:131) ~[?:?]
        at tsp.headdb.database.HeadDatabase.update(HeadDatabase.java:151) ~[?:?]
        at tsp.headdb.HeadDB.lambda$onEnable$1(HeadDB.java:48) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:102) ~[patched_1.16.5.jar:git-Paper-553]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-553]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:952) ~[patched_1.16.5.jar:git-Paper-553]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.5.jar:git-Paper-553]
        at java.lang.Thread.run(Thread.java:829) [?:?]
-----------------------------------------------

#### Example from a Plugin Extension (to add economy value ... or head purchasing) ... calls via the API
[19:08:57] [Server thread/INFO]: Ilikejuiceboxes issued server command: /ehdb
[19:09:00] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ehdb' in plugin EcoHeads v0.1-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-553]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-553]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-553]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2023) ~[patched_1.16.5.jar:git-Paper-553]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1838) ~[patched_1.16.5.jar:git-Paper-553]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1791) ~[patched_1.16.5.jar:git-Paper-553]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.5.jar:git-Paper-553]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.5.jar:git-Paper-553]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-553]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-553]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-553]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-553]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-553]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1140) ~[patched_1.16.5.jar:git-Paper-553]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Paper-553]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-553]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1094) ~[patched_1.16.5.jar:git-Paper-553]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1008) ~[patched_1.16.5.jar:git-Paper-553]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.5.jar:git-Paper-553]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.IllegalArgumentException: UUID string too large
        at java.util.UUID.fromString(UUID.java:199) ~[?:?]
        at tsp.headdb.database.HeadDatabase.getHeadsNoCache(HeadDatabase.java:131) ~[?:?]
        at tsp.headdb.database.HeadDatabase.update(HeadDatabase.java:151) ~[?:?]
        at tsp.headdb.database.HeadDatabase.getHeads(HeadDatabase.java:101) ~[?:?]
        at tsp.headdb.api.HeadAPI.getHeads(HeadAPI.java:134) ~[?:?]
        at tsp.headdb.inventory.InventoryUtils.openDatabase(InventoryUtils.java:125) ~[?:?]
        at plugins.cardcraft.inc.ecoheads.EcoHeadsCommand.onCommand(EcoHeadsCommand.java:34) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-553]

**Comment by TheSilentPro** [comment]
*comment didnt post*
Do you still have this issue? And is it only when you add the plugin extension?

**Comment by weiblecr** [comment]
I do still have the issue, I also tried removing the additional plugin and only running with HeadDB and it still occurred!

**Comment by TheSilentPro** [comment]
try downloading the latest version: https://www.spigotmc.org/resources/free-headdb-head-menu.84967/
also try removing the extension you added and see if it works on its own.
I haven't been able to reproduce this error
